application:
  name: null
deployment:
  vaultIntegrationEnabled: false
  tag: null
  resources:
    limits:
      cpu: 1
      memory: 1G
    requests:
      cpu: 500m
      memory: 128Mi
  envFrom:
    - secretRef:
        name: null
service:
  port: 80
HPA:
  maxReplicas: 4
  targetCPUUtilization: 80
ingress:
  enabled: true
  path: null
